"""Init

Revision ID: 2ca5666a7ea2
Revises: 
Create Date: 2023-11-05 01:26:51.360887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca5666a7ea2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignedport',
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staging',
    sa.Column('org_name', sa.String(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('exposed_port', sa.Integer(), nullable=False),
    sa.Column('enable_tg_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_ssl', sa.Boolean(), nullable=False),
    sa.Column('enable_websockets', sa.Boolean(), nullable=False),
    sa.Column('websockets_path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage',
    sa.Column('nginx_path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('directory', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('staging_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['port_id'], ['assignedport.id'], ),
    sa.ForeignKeyConstraint(['staging_id'], ['staging.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage')
    op.drop_table('staging')
    op.drop_table('config')
    op.drop_table('assignedport')
    # ### end Alembic commands ###
