"""Init

Revision ID: 311c93460377
Revises: 2ca5666a7ea2
Create Date: 2023-11-05 02:27:45.023593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311c93460377'
down_revision: Union[str, None] = '2ca5666a7ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staging', sa.Column('git', sa.String(), nullable=False))
    op.alter_column('staging', 'websockets_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staging', 'websockets_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('staging', 'git')
    # ### end Alembic commands ###
