"""Init

Revision ID: 7da304fb9e47
Revises: c7c5f1b68407
Create Date: 2023-11-02 08:40:56.505387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da304fb9e47'
down_revision: Union[str, None] = 'c7c5f1b68407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hostport_assigned_stage_fkey', 'hostport', type_='foreignkey')
    op.drop_column('hostport', 'assigned_stage')
    op.add_column('stage', sa.Column('port_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stage', 'hostport', ['port_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage', type_='foreignkey')
    op.drop_column('stage', 'port_id')
    op.add_column('hostport', sa.Column('assigned_stage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('hostport_assigned_stage_fkey', 'hostport', 'hostport', ['assigned_stage'], ['id'])
    # ### end Alembic commands ###
