"""Init

Revision ID: c7c5f1b68407
Revises: f0155dbe95ce
Create Date: 2023-11-02 08:39:00.927384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c5f1b68407'
down_revision: Union[str, None] = 'f0155dbe95ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage', 'port')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
