"""Init

Revision ID: f53640addfb8
Revises: 311c93460377
Create Date: 2023-11-06 12:00:23.638872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53640addfb8'
down_revision: Union[str, None] = '311c93460377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staging', sa.Column('enable_webhooks', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staging', 'enable_webhooks')
    # ### end Alembic commands ###
